name: "Push Docker Image to Dev ECR"
on:
  workflow_dispatch:
  schedule:
    # Runs at midnight UTC every day
    - cron: '0 0 * * *'
env:
  ROLE_ARN: arn:aws:iam::381491835868:role/grepr-flink-kubernetes-operator
  ROLE_SESSION_NAME: GitHub_to_AWS_via_FederatedOIDC
  AWS_REGION: us-east-1
  IMAGE_NAME: flink-k8s-operator
  ECR_URL: 381491835868.dkr.ecr.us-east-1.amazonaws.com
jobs:
  build_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: release-1.9

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: ${{ env.ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} --platform linux/amd64,linux/arm64/v8 . --file Dockerfile

      - name: Tag Docker image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:latest ${{ env.ECR_URL }}/${{ env.IMAGE_NAME }}:1.9.0

      - name: Push Docker image to ECR
        run: |
          docker push ${{ env.ECR_URL }}/${{ env.IMAGE_NAME }}:1.9.0
